# BN in backbone: HACK settings

model:
  name: fpn
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35
  backbone:
    norm_layer: "frozen_bn"
  reid_head:
    norm_layer: "frozen_bn"
train:
  output_dir: exps/exps_det_acae/exps_cuhk.fpn.freeze
  batch_size: 2
  loss_weights:
    loss_graph: 10.0
  epochs: 10
  lr_drop_epochs:
    - 5
  resume: exps/exps_det/exps_cuhk.fpn/pretrained.pth

