# cuhk with fcos based model
# using the same loss weights suggested in original paper.
# amplifying the weights of losses related to det
# using warmup training strategy in `iter_trainer`

model:
  name: fcos
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35
  backbone:
    norm_layer: "frozen_bn"
  reid_head:
    norm_layer: "frozen_bn"
train:
  output_dir: exps/exps_det_acae/exps_cuhk.fcos.freeze
  batch_size: 2
  loss_weights:
    loss_graph: 10.0
  epochs: 10
  lr_drop_epochs:
    - 5
  resume: exps/exps_det/exps_cuhk.fcos.loss_cls_5.center.iter/pretrained.pth


