# different sampling strategy, introducing more negative samples.
# in hack settings

train:
  output_dir: exps/exps_det/exps_cuhk.retinanet.sample_gt
  batch_size: 2
  loss_weights:
      loss_oim: 1.0
      loss_classifier: 2.0
      loss_box_reg: 5.0
      loss_objectness: 0.0
      loss_rpn_box_reg: 0.0
  epochs: 20
  resume: exps/exps_det/exps_cuhk.retinanet.sample_gt/checkpoint.pth

