# freeze training experiments:
# - CUHK-SYSU; 
# - w/ ACAE
# - frozen backbone
# - contrastive loss

train:
  output_dir: exps/exps_freeze/exps_cuhk.circle
  batch_size: 2
  loss_weights:
    loss_graph: 1.0
  resume: exps/baseline/baseline.pth
  epochs: 10
  lr_drop_epochs:
      - 5
model:
  backbone:
    norm_layer: "frozen_bn"
  reid_head:
    norm_layer: "frozen_bn"
  graph_head:
    loss:
      name: "circle"
      margin: 0.25
      circle_gamma: 64
eval:
  eval_all_sim: true
  eval_context: true
  graph_thred: 0.4
