# freeze training experiments:
# - CUHK-SYSU; 
# - w/ ACAE
# - frozen backbone
# - contrastive loss

train:
  output_dir: exps/exps_freeze/exps_cuhk.closs_35.stack2
  batch_size: 2
  loss_weights:
    loss_graph: 10.0
  resume: exps/baseline/baseline.pth
  epochs: 10
  lr_drop_epochs:
      - 5
model:
  backbone:
    norm_layer: "frozen_bn"
  reid_head:
    norm_layer: "frozen_bn"
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35
    num_graph_stack: 2
