# experiments:
# - PRW; 
# - w/ ACAE
# - lossw_101; 

train:
  output_dir: exps/exps_prw.oim.graph.lossw_101
  batch_size: 2
  dataset: prw
  data_root: "data/prw"
  loss_weights:
    loss_graph: 0.1
eval:
  dataset_file: prw
  dataset_path: data/prw
loss:
  oim:
    num_pids: 482
    num_cq_size: 500
