# freeze training experiments:
# - CUHK-SYSU; 
# - w/ ACAE
# - frozen backbone
# - contrastive loss

train:
  output_dir: exps/exps_train/exps_cuhk.lr_drop
  batch_size: 2
  loss_weights:
    loss_graph: 10.0
  lr_drop_epochs:
      - 10
      - 15
model:
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35

