# iou_loss: hack config
# change the range limit constrain, switch linear iou_loss to original one(-torch.log(iou)).
model:
  name: fcos
train:
  output_dir: exps/exps_det/exps_fcos.imprv.det.iou_loss
  batch_size: 2
  loss_weights:
      loss_oim: 0.0
      loss_classifier: 1.0
      loss_box_reg: 5.0
      loss_objectness: 0.0
      loss_rpn_box_reg: 0.0
  epochs: 20
  resume: exps/exps_det/exps_fcos.imprv.det.iou_loss/checkpoint0010.pth
