# cuhk with fcos based model
# using the same loss weights suggested in original paper.
# amplifying the weights of losses related to det
# using warmup training strategy in `iter_trainer`

model:
  name: fcos
train:
  output_dir: exps/exps_det/exps_cuhk.fcos.loss_cls_5.center.iter
  batch_size: 2
  loss_weights:
      loss_oim: 1.0
      loss_classifier: 5.0
      loss_box_reg: 5.0
      loss_objectness: 0.0
      loss_rpn_box_reg: 0.0
      loss_centerness: 1.0
  epochs: 20

