# BN in backbone: HACK settings

train:
  output_dir: exps/exps_det/exps_cuhk.fpn
  batch_size: 2
  loss_weights:
      loss_oim: 1.0
      loss_classifier: 1.0
      loss_box_reg: 5.0
      loss_objectness: 1.0
      loss_rpn_box_reg: 5.0

