# RetinaNet baseline with the same reid head structure
# with fpn baseline
# with sampling method the same with RetinaNet

train:
  output_dir: exps/exps_det/exps_cuhk.retinanet.fpn_reid_head.sample
  batch_size: 2
  loss_weights:
      loss_oim: 1.0
      loss_classifier: 2.0
      loss_box_reg: 5.0
      loss_objectness: 0.0
      loss_rpn_box_reg: 0.0
  epochs: 20

