# freeze training experiments:
# - CUHK-SYSU; 
# - w/ ACAE
# - frozen backbone
# - contrastive loss

train:
  output_dir: exps/exps_acae/exps_cuhk.closs_35
  batch_size: 2
  loss_weights:
    loss_graph: 10.0
model:
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35

