# freeze training experiments:
# - PRW 
# - w/ ACAE
# - contrastive loss

train:
  output_dir: exps/exps_acae/exps_prw.closs_35
  batch_size: 2
  dataset: prw
  data_root: "data/prw"
  loss_weights:
    loss_graph: 10.0
eval:
  dataset_file: prw
  dataset_path: data/prw
  use_fast_graph: True
  fast_graph_topk: 50
model:
  graph_head:
    loss:
      name: "contrastive"
      margin: 0.35
loss:
  oim:
    num_pids: 482
    num_cq_size: 500

